# .github/workflows/netlify-deploy.yml

name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Or whatever your default branch is named (could be master)

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'  # Use whatever version you're developing with
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # Add this new step to create the _redirects file
      - name: Create _redirects file
        run: |
          echo "/* https://47l5zkm2.up.railway.app/:splat 301!" > ./dist/_redirects
          cat ./dist/_redirects  # Print for verification in workflow logs

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './dist'  # Default Vite output directory
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions (${{ github.ref_name }} branch)"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
